Update Scanner.py
    print("nmap version: "sccaner.nmap_version())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?